name: Verify
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint:test
      - name: Test
        run: yarn test
